### ISSUE TITLE
Method 'where' do not work in PipelineDeals::User

### ISSUE THREAD

**Issue by joaovitoras** [PipelineDeals/pipelinedeals_api#9]
##### Someone to help me?

```ruby
PipelineDeals::User.where(conditions: {user_id: 1})

ActiveResource::ServerError: Failed.  
Response code = 500.  Response message = Internal Server Error.
from /usr/local/rvm/gems/ruby-2.1.2/gems/activeresource-4.0.0/lib/active_resource/connection.rb:156:in `handle_response'
```

**Comment by chadoh** [comment]
Hi, @joaovitoras. Sorry for the massive delay in responding to you. :frowning: 

The conditions that you can use are listed [in the api documentation](http://www.pipelinedeals.com/api/docs/resources/users). Unfortunately, you cannot search by id—but that makes sense, because if you know their id, then you can use `PipelineDeals::User.find(the_id_of_the_user)`.

I hope that helps!
